### Will allow the inclusion of the correct CPU makefile
CPU_FAMILY = cc13xx

### Include the common sensortag makefile
include $(PLATFORM_ROOT_DIR)/apros/Makefile.apros

BOARD_SOURCEFILES += leds-arch.c board.c board-i2c.c apros-sensors.c null-sensor.c
BOARD_SOURCEFILES += hdc-1010-sensor.c ekmc-1603113-sensor.c

### Add to the source dirs
CONTIKI_TARGET_DIRS += apros/t200
