### Will allow the inclusion of the correct CPU makefile
CPU_FAMILY = cc13xx

### Include the common sensortag makefile
include $(PLATFORM_ROOT_DIR)/apros/Makefile.apros

BOARD_SOURCEFILES += leds-arch.c board.c null-sensor.c apros-sensors.c adxl355.c adxl355-board-spi.c adxl355-spi-control.c

### Add to the source dirs
CONTIKI_TARGET_DIRS += apros/adxl355

