### Will allow the inclusion of the correct CPU makefile
CPU_FAMILY = cc13xx

### Include the common sensortag makefile
include $(PLATFORM_ROOT_DIR)/apros/Makefile.apros

BOARD_SOURCEFILES += adis16223-board-spi.c adis16223-sensor.c adis16223-spi-control.c
BOARD_SOURCEFILES += apros-sensors.c
BOARD_SOURCEFILES += board.c board-i2c.c button-sensor.c leds-arch.c sensor-common.c

### Add to the source dirs
CONTIKI_TARGET_DIRS += apros/adis16223
