### Will allow the inclusion of the correct CPU makefile
CPU_FAMILY = cc13xx

### Include the common sensortag makefile
include $(PLATFORM_ROOT_DIR)/apros/Makefile.apros

BOARD_SOURCEFILES += leds-arch.c board.c board-i2c.c null-sensor.c apros-sensors.c 

### Add to the source dirs
CONTIKI_TARGET_DIRS += apros/cc1310
